version: '3.3'
services:

  postgresql:
    image: library/postgres:13
    container_name: "srpt-postgresql"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      APP_SCHEMA: srpt-db
      DEFAULT_SCHEMA: public
      DB_HOST: postgresql
    ports:
      - 7432:5432
    restart: always

  app:
    image: srpt:1.0.0
    container_name: "srpt-app"
    ports:
      - 8081:8081
    depends_on:
      - postgresql
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always