spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:7432}/srpt-db
    password: ${POSTGRES_PASSWORD:12345678}
    username: ${POSTGRES_USER:srpt-db}
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000

document:
  signature: SIGN
  api:
    requestLimit: 5
    timeUnit: SECONDS
